version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: notes_mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: GeronimoCordoba
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      timeout: 20s
      retries: 10

  backend:
    build: .
    container_name: notes_backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_DATABASE=GeronimoCordoba
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: notes_frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
