version: '3.8'
services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql_local.cnf:/etc/mysql/conf.d/mysql_local.cnf:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: geronimocordoba
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  api:
    depends_on:
      - db
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_DATABASE: GeronimoCordoba
      DB_PORT: 3306
volumes:
  db_data:
